.TH hildon\-input\-method 1 2006-11-30 3.0 "Hildon Input Method manual"
.SH NAME
hildon\-input\-method \- invoke Hildon Input Method main UI
.SH SYNOPSIS
.B hildon\-input\-method
.SH DESCRIPTION
\fBhildon\-input\-method\fP is the main UI of the input method.
.SH OPTIONS
No options
.SH AUTHOR
\fBhildon\-input\-method\fP was written by Hildon Input Method team.

